### all post json has NO TRAILING "," !!!
### https://github.com/Huachao/vscode-restclient

### Test remote
GET 142.93.217.249:3000/ic/test

### root
GET http://localhost:3000

### hello
GET http://localhost:3000/hello

### get_user_by_id
GET http://localhost:3000/user/100
### exactmatch
GET http://localhost:3000/user/092
### query_params
GET http://localhost:3000/query_params?code=hello world&user_id=155

### query_headers: after the request line to first empty line
GET http://localhost:3000/query_headers
User-Agent: rest-client
Accept: */*
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

### query_custom_headers
GET http://localhost:3000/query_custom_headers
User-Agent: rest-client
Accept: */*
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json
alg: HS256
typ: JWT
Authorization: Bearer vwig.3435u2ng.lv6iria

### get_config
GET http://localhost:3000/get_config

### get_custom_middleware
GET http://localhost:3000/get_custom_middleware
User-Agent: rest-client
Accept: */*
security-level: "abc security 9"

### always_errors
GET http://localhost:3000/always_errors

### get_body_string
POST http://localhost:3000/get_body_string
content-type: application/json

{
  "get_body_string hello"
}

### validate_struct_input
POST http://localhost:3000/validate_struct_input
content-type: application/json

{
  "username": "John Doe",
  "password": "12345678",
  "email": "abc@domain.com"
}
### validate_struct_input: fail in password length
POST http://localhost:3000/validate_struct_input
content-type: application/json

{
  "username": "John Doe",
  "password": "1234567",
  "email": "abc"
}

### get_task_by_id
GET http://localhost:3000/tasks/5

### get_task_by_id
GET http://localhost:3000/tasks/999
### get_task_all
GET http://localhost:3000/tasks
### get_task_all + priority
GET http://localhost:3000/tasks?priority=A
### get_task_all + priority
GET http://localhost:3000/tasks?priority=B
### get_task_all + priority
GET http://localhost:3000/tasks?priority=
### get_task_all + priority
GET http://localhost:3000/tasks?priority=D
### get_task_all + priority
GET http://localhost:3000/tasks?title=title1
### get_task_all + priority
GET http://localhost:3000/tasks?priority=A&title=title1

### add_task
POST http://localhost:3000/add_task
content-type: application/json

{
  "title": "title1",
  "priority": "B",
  "description": "description B"
}

### replace_task
PUT http://localhost:3000/tasks/5
content-type: application/json

{
    "task_id": 999,
    "title": "title2",
    "priority": "AB"
}
### get_task_by_id
GET http://localhost:3000/tasks/5
### update_partial_task
PATCH http://localhost:3000/tasks/5
content-type: application/json

{
    "task_id": 999,
    "title": "title 22",
    "priority": "ABC"
}
### update_partial_task
PATCH http://localhost:3000/tasks/5
content-type: application/json

{
    "task_id": 999,
    "title": "title 22",
    "priority": "AB",
    "description": "some description"
}
### update_partial_task
PATCH http://localhost:3000/tasks/5
content-type: application/json

{
    "task_id": 999,
    "title": "title 22",
    "priority": "AB",
    "description": null
}

### Get Google
GET www.google.com 
